package textedit_test

import (
	"strings"
	"testing"

	"github.com/jtarchie/topbanana/internal/textedit"
)

// ValidateTextPath is the gate the MCP write and edit tools share. Two
// properties matter enough to pin: an author can maintain their own text
// assets in place (the whole reason it's wider than ValidateHTMLPath), and the
// platform-managed keyspace stays unreachable through a generic file write —
// `functions/` because executable handlers have their own tools and an
// enable_functions gate, `_state/` because it holds the site's captured form
// submissions.
func TestValidateTextPath(t *testing.T) {
	t.Parallel()

	allowed := []string{
		"index.html",
		"about.html",
		"blog/post-1.html",
		"fonts.css",
		"assets/theme.css",
		"assets/logo.svg",
		"app.js",
		"readme.md",
		"robots.txt",
		"data/menu.json",
	}
	for _, p := range allowed {
		err := textedit.ValidateTextPath(p)
		if err != nil {
			t.Errorf("ValidateTextPath(%q) = %v; want allowed", p, err)
		}
	}

	rejected := map[string]string{
		"functions/submit.js":  "reserved prefix",
		"functions/nested.js":  "reserved prefix",
		"_state/data.json":     "reserved prefix",
		"_pending/photo.svg":   "reserved prefix",
		"nested/_state/x.json": "reserved prefix",
		".topbanana.json":      "reserved",
		".bloomhollow.json":    "reserved",
		"../escape.html":       "",
		"/absolute.html":       "",
		"page.php":             "unsupported extension",
		"archive.zip":          "unsupported extension",
		"noextension":          "unsupported extension",
		"":                     "",
	}
	for p, wantSubstr := range rejected {
		err := textedit.ValidateTextPath(p)
		if err == nil {
			t.Errorf("ValidateTextPath(%q) = nil; want rejected", p)
			continue
		}
		if wantSubstr != "" && !strings.Contains(err.Error(), wantSubstr) {
			t.Errorf("ValidateTextPath(%q) = %q; want it to mention %q", p, err, wantSubstr)
		}
	}
}

// Deletion needs its own gate. It must reach uploaded images (which no text
// write can produce) while keeping the platform-managed paths unreachable —
// deleting the sidecar orphans the site, and deleting the state blob destroys
// every captured submission.
func TestValidateDeletePath(t *testing.T) {
	t.Parallel()

	allowed := []string{
		"index.html", "fonts.css", "app.js", "sitemap.xml",
		"assets/logo.png", "assets/photo.jpeg", "assets/icon.ico", "assets/art.svg",
	}
	for _, p := range allowed {
		err := textedit.ValidateDeletePath(p)
		if err != nil {
			t.Errorf("ValidateDeletePath(%q) = %v; want allowed", p, err)
		}
	}

	rejected := []string{
		".topbanana.json",     // orphans the site: owner, template, domains
		"_state/data.json",    // every form submission
		"_pending/x.jpg",      // un-approved photo-wall bytes
		"functions/submit.js", // has delete_function
		"app.css",             // generated by the CSS pipeline
		"../../etc/passwd",
		"index.php",
	}
	for _, p := range rejected {
		err := textedit.ValidateDeletePath(p)
		if err == nil {
			t.Errorf("ValidateDeletePath(%q) = nil; want rejected", p)
		}
	}
}

// app.css is recompiled and overwritten by every build and every lint_site, so
// a write there is guaranteed to be destroyed. Reserved on both gates.
func TestGeneratedStylesheetIsNotWritable(t *testing.T) {
	t.Parallel()

	err := textedit.ValidateTextPath("app.css")
	if err == nil {
		t.Error("ValidateTextPath(app.css) = nil; the CSS pipeline overwrites it")
	}
	err = textedit.ValidateHTMLPath("app.css")
	if err == nil {
		t.Error("ValidateHTMLPath(app.css) = nil; the CSS pipeline overwrites it")
	}
	// A differently-named stylesheet is the author's own and stays writable.
	err = textedit.ValidateTextPath("fonts.css")
	if err != nil {
		t.Errorf("ValidateTextPath(fonts.css) = %v; want allowed", err)
	}
}

// ValidateHTMLPath allowed `_`-prefixed segments before the hidden-segment
// check existed, which meant an HTML write could land inside the in-slug
// reserved directories. Pin that it can't.
func TestValidateHTMLPath_RejectsReservedDirectories(t *testing.T) {
	t.Parallel()

	for _, p := range []string{"_state/page.html", "_pending/page.html", "nested/_x/page.html"} {
		err := textedit.ValidateHTMLPath(p)
		if err == nil {
			t.Errorf("ValidateHTMLPath(%q) = nil; want rejected", p)
		}
	}
	// The ordinary cases still pass, including underscores mid-segment.
	for _, p := range []string{"index.html", "blog/post_2.html", "a_b.html"} {
		err := textedit.ValidateHTMLPath(p)
		if err != nil {
			t.Errorf("ValidateHTMLPath(%q) = %v; want allowed", p, err)
		}
	}
	// And it stays HTML-only: the wider text extensions are ValidateTextPath's
	// business, not this one's.
	err := textedit.ValidateHTMLPath("fonts.css")
	if err == nil {
		t.Error("ValidateHTMLPath(fonts.css) = nil; want rejected")
	}
}
